@startuml

left to right direction
package "Producers" as producers {
    rectangle "producer 1" as prod_1
    rectangle "producer 2" as prod_2
    rectangle "producer 3" as prod_3
}

 
rectangle "Queue" as queue

rectangle "Consumer" as consumer 

database "Database\n(Warehouse)" as db
database "Neo4j" as neo4j

rectangle "Neo4j Loader" as neo4j_loader

rectangle "Scheduler" as scheduler

prod_1 --> queue : Publish data
prod_2 --> queue : Publish data
prod_3 --> queue : Publish data

consumer <--> queue : Consume the data
consumer --> db : Store data

neo4j_loader <--> db : Read data\nfrom Datawarehouse
neo4j_loader --> neo4j : Write in Neo4j
scheduler --> neo4j_loader : Run Neo4j\nLoader job
@endumls